### ISSUE TITLE
Integrate add tree with APIs

### ISSUE THREAD

**Issue by Jagdeep1** [ti-app/tia-client#16]

**Comment by itachiRedhair** [comment]
@Jagdeep1 @muraliprajapati  @souvikckr  Add Api is integrated. Small changes like below are required:
1) Close the add new spot screen and fetch the trees again.
2) Show current location icon on the home map screen.
3) Show tree marker (location where new tree group is added) at center of map on the add new spot screen. User can move the map to select a tree group location on add new spot screen.
4) When tree group is added with the add api, in database multiple trees (based on the number of plants provided) with the same location are added. This is causing the trees for the same tree group to be clustered in the UI (because of the same location). Right now, only on clicking individual trees (not the cluster), tree details page will open.

**Comment by itachiRedhair** [comment]
You can find the latest build with the add tree integration here:
[https://expo.io/artifacts/a8cde0f5-293f-4354-b453-c6361de91edd](url)

**Comment by Jagdeep1** [comment]
@itachiRedhair getting this error 
```
[22:45:46] Unable to resolve "@expo/vector-icons/Ionicons" from "node_modules/native-base/dist/src/basic/IconNB.js"
```

**Comment by itachiRedhair** [comment]
try deleting `node_modules` and do `yarn install`

**Comment by Jagdeep1** [comment]
Tried ``` yarn install ``` but still getting the following error
```
[10:57:24] Unable to resolve "./DrawerLayout" from "node_modules/react-navigation-drawer/dist/views/DrawerView.js"
[10:57:24] Failed building JavaScript bundle.
```

**Comment by Jagdeep1** [comment]
Fixed by pinning down version of react-navigation 
```
"react-navigation": "3.0.9"
```
